require("lk.plugins-setup")
require("lk.core.options")
require("lk.core.keymaps")
require("lk.core.colorscheme")
require("lk.plugins.comment")
require("lk.plugins.nvim-tree")
require("lk.plugins.lualine")
require("lk.plugins.telescope")
require("lk.plugins.nvim-cmp")
require("lk.plugins.lsp.neodev")
require("lk.plugins.lsp.mason")
require("lk.plugins.lsp.lspsaga")
require("lk.plugins.lsp.lspconfig")
require("lk.plugins.lsp.null-ls")
require("lk.plugins.crates")
require("lk.plugins.fidget")
require("lk.plugins.trouble")
require("lk.plugins.todo-comments")
require("lk.plugins.autopairs")
require("lk.plugins.treesitter")
require("lk.plugins.treesitter-context")
-- require("lk.plugins.gitsigns")
require("lk.plugins.toggleterm")
require("lk.plugins.colorizer")
-- require("lk.plugins.modes")
require("lk.plugins.whichkey")
require("lk.plugins.cheatsheet")
require("lk.plugins.leap")
-- require("lk.plugins.litee")
-- require("lk.plugins.ide")
